package cnae;

import GUI.AsignaturaIF;
import GUI.AsistenciaIF;
import GUI.CalendarioIF;
import GUI.CarreraIF;
import GUI.DocenteIF;
import GUI.EstructuraEvaluacionIF;
import GUI.EstudianteIF;
import GUI.TipoEvaluacionIF;
import GUI.FacultadIF;
import GUI.TipoActividadIF;
import GUI.UniversidadIF;
import GUI.repAsignaturaIF;
import GUI.repCarreraIF;
import GUI.repDocenteIF;
import GUI.repFacultadIF;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import GUI.repUniversidadIF;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author PabloAntonio
 */
public class Cnae extends javax.swing.JFrame {

    /**
     * Creates new form cnae
     */
    public Cnae() {
        initComponents();
        setContentPane(Escritorio);
        //Escritorio.setPreferredSize(new java.awt.Dimension(784, 541));
        Escritorio.setBackground(new java.awt.Color(0,128,192));
        //Escritorio.setPreferredSize(new java.awt.Dimension(784, 541));
    }
    
    public void centerJIF(JInternalFrame jif) {
    Dimension desktopSize = Escritorio.getSize();
    Dimension jInternalFrameSize = jif.getSize();
    int width = (desktopSize.width - jInternalFrameSize.width) / 2;
    int height = (desktopSize.height - jInternalFrameSize.height) / 2;
    jif.setLocation(width, height);
    jif.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuPrArchivo = new javax.swing.JMenu();
        MnuSalir = new javax.swing.JMenuItem();
        MnuCambioAsignatura = new javax.swing.JMenuItem();
        MnuPrOperaciones = new javax.swing.JMenu();
        MnuRegistroAsistencia = new javax.swing.JMenuItem();
        MnuEvaluacion = new javax.swing.JMenuItem();
        MnuPrCatalogo = new javax.swing.JMenu();
        MnuEstudiantes = new javax.swing.JMenuItem();
        MnuCalendario = new javax.swing.JMenuItem();
        MnuTipoEvaluacion = new javax.swing.JMenuItem();
        MnuTipoActividad = new javax.swing.JMenuItem();
        MnuEstructuraEvaluacion = new javax.swing.JMenuItem();
        MnuAsignatura = new javax.swing.JMenuItem();
        MnuCarreras = new javax.swing.JMenuItem();
        MnuFacultades = new javax.swing.JMenuItem();
        MnuUniversidades = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        MnuPrReportes = new javax.swing.JMenu();
        MnuRepAsistencia = new javax.swing.JMenuItem();
        MnuNotas = new javax.swing.JMenuItem();
        mnuCatalogos = new javax.swing.JMenu();
        mnuUniversidad = new javax.swing.JMenuItem();
        mnuFacultad = new javax.swing.JMenuItem();
        mnuCarrera = new javax.swing.JMenuItem();
        mnuAsignatura = new javax.swing.JMenuItem();
        MnuRepEstudiantes = new javax.swing.JMenuItem();
        MnuRepTipoEvaluacion = new javax.swing.JMenuItem();
        MnuRepCalendario = new javax.swing.JMenuItem();
        MnuRepTipoActividad = new javax.swing.JMenuItem();
        MnuRepEstructuraEvaluacion = new javax.swing.JMenuItem();
        MnuRepDocente = new javax.swing.JMenuItem();
        MnuPrUtilitarios = new javax.swing.JMenu();
        MnuCambioContrasena = new javax.swing.JMenuItem();
        MnuRespaldoDatos = new javax.swing.JMenuItem();
        MnuRecuperacionDatos = new javax.swing.JMenuItem();
        MnuPrAyuda = new javax.swing.JMenu();
        MnuHelp = new javax.swing.JMenuItem();
        MnuAcercaDe = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MnuPrArchivo.setMnemonic('A');
        MnuPrArchivo.setText("Archivo");

        MnuSalir.setMnemonic('s');
        MnuSalir.setText("Salir");
        MnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSalirActionPerformed(evt);
            }
        });
        MnuPrArchivo.add(MnuSalir);

        MnuCambioAsignatura.setMnemonic('c');
        MnuCambioAsignatura.setText("Cambiar de Asignatura");
        MnuCambioAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCambioAsignaturaActionPerformed(evt);
            }
        });
        MnuPrArchivo.add(MnuCambioAsignatura);

        jMenuBar1.add(MnuPrArchivo);

        MnuPrOperaciones.setMnemonic('o');
        MnuPrOperaciones.setText("Operaciones");

        MnuRegistroAsistencia.setMnemonic('r');
        MnuRegistroAsistencia.setText("Registro de Asistencia");
        MnuRegistroAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuRegistroAsistenciaActionPerformed(evt);
            }
        });
        MnuPrOperaciones.add(MnuRegistroAsistencia);

        MnuEvaluacion.setMnemonic('e');
        MnuEvaluacion.setText("Evaluación");
        MnuEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEvaluacionActionPerformed(evt);
            }
        });
        MnuPrOperaciones.add(MnuEvaluacion);

        jMenuBar1.add(MnuPrOperaciones);

        MnuPrCatalogo.setMnemonic('c');
        MnuPrCatalogo.setText("Catálogo");

        MnuEstudiantes.setMnemonic('e');
        MnuEstudiantes.setText("Estudiantes");
        MnuEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEstudiantesActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuEstudiantes);

        MnuCalendario.setMnemonic('a');
        MnuCalendario.setLabel("Calendario");
        MnuCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCalendarioActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuCalendario);

        MnuTipoEvaluacion.setMnemonic('t');
        MnuTipoEvaluacion.setText("Tipo de Evaluación");
        MnuTipoEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuTipoEvaluacionActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuTipoEvaluacion);

        MnuTipoActividad.setMnemonic('p');
        MnuTipoActividad.setText("Tipo de Actividad");
        MnuTipoActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuTipoActividadActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuTipoActividad);

        MnuEstructuraEvaluacion.setMnemonic('s');
        MnuEstructuraEvaluacion.setText("Estructura de Evaluación");
        MnuEstructuraEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEstructuraEvaluacionActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuEstructuraEvaluacion);

        MnuAsignatura.setMnemonic('g');
        MnuAsignatura.setText("Asignaturas");
        MnuAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAsignaturaActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuAsignatura);

        MnuCarreras.setMnemonic('r');
        MnuCarreras.setText("Carreras");
        MnuCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCarrerasActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuCarreras);

        MnuFacultades.setMnemonic('f');
        MnuFacultades.setText("Facultades");
        MnuFacultades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuFacultadesActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuFacultades);

        MnuUniversidades.setMnemonic('u');
        MnuUniversidades.setText("Univerdades");
        MnuUniversidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuUniversidadesActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(MnuUniversidades);

        jMenuItem1.setMnemonic('d');
        jMenuItem1.setText("Docente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MnuPrCatalogo.add(jMenuItem1);

        jMenuBar1.add(MnuPrCatalogo);

        MnuPrReportes.setMnemonic('r');
        MnuPrReportes.setText("Reportes");

        MnuRepAsistencia.setMnemonic('r');
        MnuRepAsistencia.setText("Asistencia");
        MnuPrReportes.add(MnuRepAsistencia);

        MnuNotas.setMnemonic('n');
        MnuNotas.setText("Notas");
        MnuPrReportes.add(MnuNotas);

        mnuCatalogos.setMnemonic('c');
        mnuCatalogos.setText("Catálogos");
        mnuCatalogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCatalogosActionPerformed(evt);
            }
        });

        mnuUniversidad.setMnemonic('u');
        mnuUniversidad.setText("Universidades");
        mnuUniversidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUniversidadActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuUniversidad);

        mnuFacultad.setMnemonic('f');
        mnuFacultad.setText("Facultades");
        mnuFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacultadActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuFacultad);

        mnuCarrera.setMnemonic('r');
        mnuCarrera.setText("Carreras");
        mnuCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCarreraActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuCarrera);

        mnuAsignatura.setMnemonic('g');
        mnuAsignatura.setText("Asignaturas");
        mnuAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAsignaturaActionPerformed(evt);
            }
        });
        mnuCatalogos.add(mnuAsignatura);

        MnuRepEstudiantes.setMnemonic('e');
        MnuRepEstudiantes.setText("Estudiantes");
        mnuCatalogos.add(MnuRepEstudiantes);

        MnuRepTipoEvaluacion.setMnemonic('t');
        MnuRepTipoEvaluacion.setText("Tipo de Evaluación");
        mnuCatalogos.add(MnuRepTipoEvaluacion);

        MnuRepCalendario.setMnemonic('l');
        MnuRepCalendario.setText("Calendario");
        mnuCatalogos.add(MnuRepCalendario);

        MnuRepTipoActividad.setMnemonic('i');
        MnuRepTipoActividad.setText("Tipo Actividad");
        mnuCatalogos.add(MnuRepTipoActividad);

        MnuRepEstructuraEvaluacion.setMnemonic('v');
        MnuRepEstructuraEvaluacion.setText("Estructura de Evaluación");
        mnuCatalogos.add(MnuRepEstructuraEvaluacion);

        MnuRepDocente.setMnemonic('d');
        MnuRepDocente.setText("Docente");
        MnuRepDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuRepDocenteActionPerformed(evt);
            }
        });
        mnuCatalogos.add(MnuRepDocente);

        MnuPrReportes.add(mnuCatalogos);

        jMenuBar1.add(MnuPrReportes);

        MnuPrUtilitarios.setMnemonic('u');
        MnuPrUtilitarios.setText("Utilitarios");

        MnuCambioContrasena.setMnemonic('c');
        MnuCambioContrasena.setText("Cambio Contraseña");
        MnuPrUtilitarios.add(MnuCambioContrasena);

        MnuRespaldoDatos.setMnemonic('r');
        MnuRespaldoDatos.setText("Respaldo de Datos");
        MnuPrUtilitarios.add(MnuRespaldoDatos);

        MnuRecuperacionDatos.setMnemonic('d');
        MnuRecuperacionDatos.setText("Recuperación de Datos");
        MnuPrUtilitarios.add(MnuRecuperacionDatos);

        jMenuBar1.add(MnuPrUtilitarios);

        MnuPrAyuda.setMnemonic('y');
        MnuPrAyuda.setText("Ayuda");

        MnuHelp.setMnemonic('a');
        MnuHelp.setText("Ayuda");
        MnuPrAyuda.add(MnuHelp);

        MnuAcercaDe.setMnemonic('c');
        MnuAcercaDe.setText("Acerca de");
        MnuPrAyuda.add(MnuAcercaDe);

        jMenuBar1.add(MnuPrAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEvaluacionActionPerformed
        TipoEvaluacionIF evaluacionVent = new TipoEvaluacionIF();
        centerJIF(evaluacionVent);
        Escritorio.add(evaluacionVent);
    }//GEN-LAST:event_MnuEvaluacionActionPerformed

    private void MnuCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCalendarioActionPerformed
        CalendarioIF calendarioVent = new CalendarioIF();
        centerJIF(calendarioVent);
        Escritorio.add(calendarioVent);
    }//GEN-LAST:event_MnuCalendarioActionPerformed

    private void MnuTipoActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuTipoActividadActionPerformed
        TipoActividadIF tipoActividadVent = new TipoActividadIF();
        centerJIF(tipoActividadVent);
        Escritorio.add(tipoActividadVent);
        
    }//GEN-LAST:event_MnuTipoActividadActionPerformed

    private void MnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSalirActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Desea Salir?","Confirmar",
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.ERROR_MESSAGE);
        if(i==JOptionPane.OK_OPTION){
            System.exit(0);}
    }//GEN-LAST:event_MnuSalirActionPerformed

    private void MnuUniversidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuUniversidadesActionPerformed
        UniversidadIF universidadVent = new UniversidadIF();
        centerJIF(universidadVent);
        Escritorio.add(universidadVent);
    }//GEN-LAST:event_MnuUniversidadesActionPerformed

    private void MnuFacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuFacultadesActionPerformed
        FacultadIF facultadVent = new FacultadIF();
        centerJIF(facultadVent);
        Escritorio.add(facultadVent);
    }//GEN-LAST:event_MnuFacultadesActionPerformed

    private void MnuCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCarrerasActionPerformed
        CarreraIF carreraVent = new CarreraIF();
        centerJIF(carreraVent);
        Escritorio.add(carreraVent);
    }//GEN-LAST:event_MnuCarrerasActionPerformed

    private void MnuAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAsignaturaActionPerformed
        AsignaturaIF asignaturaVent = new AsignaturaIF();
        centerJIF(asignaturaVent);
        Escritorio.add(asignaturaVent);
    }//GEN-LAST:event_MnuAsignaturaActionPerformed

    private void MnuEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEstudiantesActionPerformed
        EstudianteIF estudianteVent = new EstudianteIF();
        centerJIF(estudianteVent);
        Escritorio.add(estudianteVent);
    }//GEN-LAST:event_MnuEstudiantesActionPerformed

    private void MnuTipoEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuTipoEvaluacionActionPerformed
        TipoEvaluacionIF tipoevaluacionVent = new TipoEvaluacionIF();
        centerJIF(tipoevaluacionVent);
        Escritorio.add(tipoevaluacionVent);
    }//GEN-LAST:event_MnuTipoEvaluacionActionPerformed

    private void mnuCatalogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCatalogosActionPerformed
        
    }//GEN-LAST:event_mnuCatalogosActionPerformed

    private void mnuUniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUniversidadActionPerformed
        repUniversidadIF universidadRep = new repUniversidadIF();
        centerJIF(universidadRep);
        Escritorio.add(universidadRep);
    }//GEN-LAST:event_mnuUniversidadActionPerformed

    private void mnuFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacultadActionPerformed
        repFacultadIF facultadRep = new repFacultadIF();
        centerJIF(facultadRep);
        Escritorio.add(facultadRep);               
    }//GEN-LAST:event_mnuFacultadActionPerformed

    private void mnuCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCarreraActionPerformed
        repCarreraIF carreraRep = new repCarreraIF();
        centerJIF(carreraRep);
        Escritorio.add(carreraRep);
    }//GEN-LAST:event_mnuCarreraActionPerformed

    private void mnuAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAsignaturaActionPerformed
        repAsignaturaIF asignaturaRep = new repAsignaturaIF();
        centerJIF(asignaturaRep);
        Escritorio.add(asignaturaRep);
    }//GEN-LAST:event_mnuAsignaturaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DocenteIF  docenteVent = new DocenteIF();
        centerJIF(docenteVent);
        Escritorio.add(docenteVent);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MnuEstructuraEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEstructuraEvaluacionActionPerformed
        EstructuraEvaluacionIF estructuraVent = new EstructuraEvaluacionIF();
        centerJIF(estructuraVent);
        Escritorio.add(estructuraVent);
    }//GEN-LAST:event_MnuEstructuraEvaluacionActionPerformed

    private void MnuRegistroAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuRegistroAsistenciaActionPerformed
        AsistenciaIF asistenciaVent = new AsistenciaIF();
        centerJIF(asistenciaVent);
        Escritorio.add(asistenciaVent);
    }//GEN-LAST:event_MnuRegistroAsistenciaActionPerformed

    private void MnuRepDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuRepDocenteActionPerformed
        repDocenteIF docenteRep = new repDocenteIF();
        centerJIF(docenteRep);
        Escritorio.add(docenteRep);
    }//GEN-LAST:event_MnuRepDocenteActionPerformed

    private void MnuCambioAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCambioAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuCambioAsignaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cnae.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Cnae Aplicacion = new Cnae();
                Aplicacion.setVisible(true);                
                Aplicacion.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem MnuAcercaDe;
    private javax.swing.JMenuItem MnuAsignatura;
    private javax.swing.JMenuItem MnuCalendario;
    private javax.swing.JMenuItem MnuCambioAsignatura;
    private javax.swing.JMenuItem MnuCambioContrasena;
    private javax.swing.JMenuItem MnuCarreras;
    private javax.swing.JMenuItem MnuEstructuraEvaluacion;
    private javax.swing.JMenuItem MnuEstudiantes;
    private javax.swing.JMenuItem MnuEvaluacion;
    private javax.swing.JMenuItem MnuFacultades;
    private javax.swing.JMenuItem MnuHelp;
    private javax.swing.JMenuItem MnuNotas;
    private javax.swing.JMenu MnuPrArchivo;
    private javax.swing.JMenu MnuPrAyuda;
    private javax.swing.JMenu MnuPrCatalogo;
    private javax.swing.JMenu MnuPrOperaciones;
    private javax.swing.JMenu MnuPrReportes;
    private javax.swing.JMenu MnuPrUtilitarios;
    private javax.swing.JMenuItem MnuRecuperacionDatos;
    private javax.swing.JMenuItem MnuRegistroAsistencia;
    private javax.swing.JMenuItem MnuRepAsistencia;
    private javax.swing.JMenuItem MnuRepCalendario;
    private javax.swing.JMenuItem MnuRepDocente;
    private javax.swing.JMenuItem MnuRepEstructuraEvaluacion;
    private javax.swing.JMenuItem MnuRepEstudiantes;
    private javax.swing.JMenuItem MnuRepTipoActividad;
    private javax.swing.JMenuItem MnuRepTipoEvaluacion;
    private javax.swing.JMenuItem MnuRespaldoDatos;
    private javax.swing.JMenuItem MnuSalir;
    private javax.swing.JMenuItem MnuTipoActividad;
    private javax.swing.JMenuItem MnuTipoEvaluacion;
    private javax.swing.JMenuItem MnuUniversidades;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mnuAsignatura;
    private javax.swing.JMenuItem mnuCarrera;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenuItem mnuFacultad;
    private javax.swing.JMenuItem mnuUniversidad;
    // End of variables declaration//GEN-END:variables
}
